# App
spring.application.name=user-service
spring.docker.compose.enabled=false
#spring.docker.compose.file=../docker-compose.infra.yml
#spring.docker.compose.lifecycle-management=NONE

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rent_flow}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Keycloak
keycloak.server-url=${KEYCLOAK_SERVER_URL:http://localhost:8180}
keycloak.target-realm=${KEYCLOAK_TARGET_REALM:rentflow}
keycloak.client-id=${KEYCLOAK_CLIENT_ID:user-service-client}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:your-secret-here}

# Spring Security OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/rentflow